import { Producto, Categoria, Pedido } from '@/types'

export const productos: Producto[] = [
  {
    id: 'prod-001',
    nombre: 'Ventana Corrediza de Aluminum 150x120cm',
    descripcion: 'Ventana de aluminio con apertura corrediza de doble riel. Vidrio templado de 4mm. Incluye mosquito y mosquitero de aluminio. Rodamientos de acero inoxidable.',
    precio: 68500,
    stock: 8,
    categoria: 'ventanas',
    material: 'aluminio',
    color: 'Blanco',
    imagenes: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600'],
    relacionados: ['prod-002', 'prod-006', 'prod-011'],
  },
  {
    id: 'prod-002',
    nombre: 'Ventana Proyectante 90x60cm',
    descripcion: 'Ventana con apertura hacia afuera tipo proyectante. Ideal para baños y espacios pequeños. Bisagras de acero inoxidable. Sellado perimetral anti-agua.',
    precio: 42500,
    stock: 12,
    categoria: 'ventanas',
    material: 'aluminio',
    color: 'Natural',
    imagenes: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600'],
    relacionados: ['prod-001', 'prod-003', 'prod-012'],
  },
  {
    id: 'prod-003',
    nombre: 'Ventana Fija de Aluminum 200x100cm',
    descripcion: 'Ventana fija sin apertura. Marco de aluminio de 40mm. Vidrio laminado 3+3 para mayor seguridad y aislación térmica. Ideal para fachadas.',
    precio: 55000,
    stock: 3,
    categoria: 'ventanas',
    material: 'aluminio',
    color: 'Gris Anodizado',
    imagenes: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600'],
    relacionados: ['prod-001', 'prod-004', 'prod-011'],
  },
  {
    id: 'prod-004',
    nombre: 'Ventana Guillotina de PVC 120x100cm',
    descripcion: 'Ventana con apertura vertical tipo guillotina. Marco de PVC blanco con refuerzo de acero. Doble vidrio hermético. Aislación térmica y acústica superior.',
    precio: 78000,
    stock: 0,
    categoria: 'ventanas',
    material: 'pvc',
    color: 'Blanco',
    imagenes: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600'],
    relacionados: ['prod-001', 'prod-002', 'prod-009'],
  },
  {
    id: 'prod-005',
    nombre: 'Puerta de Chapa 80x200cm',
    descripcion: 'Puerta de entrada de chapa de acero galvanizado. Doble refuerzoular interior. Cerradura de seguridad de 3 puntos. Pintura epoxi horneada antióxido.',
    precio: 95000,
    stock: 5,
    categoria: 'puertas',
    material: 'aluminio',
    color: 'Negro',
    imagenes: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600'],
    relacionados: ['prod-006', 'prod-007', 'prod-011'],
  },
  {
    id: 'prod-006',
    nombre: 'Puerta Corrediza de Patio 180x200cm',
    descripcion: 'Puerta para patio con dos hojas corredizas sobre riel de aluminio. Marco reforzado con rodamientos de nylon. Incluye cerradura y llave.',
    precio: 145000,
    stock: 4,
    categoria: 'puertas',
    material: 'aluminio',
    color: 'Blanco',
    imagenes: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600'],
    relacionados: ['prod-001', 'prod-005', 'prod-010'],
  },
  {
    id: 'prod-007',
    nombre: 'Puerta Plegadiza de Aluminum 120x210cm',
    descripcion: 'Puerta plegadiza de 4 paneles para ambientes amplios. Aluminium natural con acabado mate. Ruedas nylon con rulemanes. Muy fácil instalación.',
    precio: 118000,
    stock: 2,
    categoria: 'puertas',
    material: 'aluminio',
    color: 'Natural',
    imagenes: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600'],
    relacionados: ['prod-005', 'prod-006', 'prod-008'],
  },
  {
    id: 'prod-008',
    nombre: 'Perfil U de Aluminum 6 metros',
    descripcion: 'Perfil de aluminium en U para estructuras, cerramientos y refacciones. Espesor 1.5mm. Largo 6 metros. Excelente para carpinterías artesanales.',
    precio: 12500,
    stock: 45,
    categoria: 'perfiles',
    material: 'aluminio',
    color: 'Natural',
    imagenes: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600'],
    relacionados: ['prod-009', 'prod-010', 'prod-011'],
  },
  {
    id: 'prod-009',
    nombre: 'Perfil Angular 20x20mm x 6m',
    descripcion: 'Perfil angular de aluminium para refuerzos, terminaciones y estructuras. Medida 20x20mm. Espesor 1.2mm. Largo 6 metros. Alta resistencia mecánica.',
    precio: 8900,
    stock: 60,
    categoria: 'perfiles',
    material: 'aluminio',
    color: 'Natural',
    imagenes: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600'],
    relacionados: ['prod-008', 'prod-010', 'prod-012'],
  },
  {
    id: 'prod-010',
    nombre: 'Marcos para Ventana PVC 150x120cm',
    descripcion: 'Marco de PVC blanco de alta densidad con refuerzo de aluminium galvanizado. Para ventana corrediza de 150x120cm. Incluye burletes de EPDM.',
    precio: 65000,
    stock: 7,
    categoria: 'perfiles',
    material: 'pvc',
    color: 'Blanco',
    imagenes: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600'],
    relacionados: ['prod-004', 'prod-008', 'prod-011'],
  },
  {
    id: 'prod-011',
    nombre: 'Kit de Ruedas para Puerta Corrediza',
    descripcion: 'Kit de 4 ruedas de nylon con rulemanes de acero. Capacidad 150kg por rueda. Para puertas de hasta 200kg. Incluye tornillos de instalación.',
    precio: 18500,
    stock: 25,
    categoria: 'accesorios',
    material: 'mixto',
    color: 'Gris',
    imagenes: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600'],
    relacionados: ['prod-006', 'prod-007', 'prod-012'],
  },
  {
    id: 'prod-012',
    nombre: 'Cerradura de Seguridad para Puerta',
    descripcion: 'Cerradura de embutir con 3 puntos de cierre. Cilindro de seguridad con llave cuadrada reforzada. Compatible con puertas de aluminium y madera.',
    precio: 24500,
    stock: 15,
    categoria: 'accesorios',
    material: 'aluminio',
    color: 'Gris',
    imagenes: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600'],
    relacionados: ['prod-005', 'prod-006', 'prod-011'],
  },
]

export const categorias: Categoria[] = [
  {
    id: 'ventanas',
    nombre: 'Ventanas',
    descripcion: 'Ventanas de aluminium y PVC para residential y comercial. Corredizas, proyectantes y fijas.',
    icono: 'LayoutPanelTop',
    imagen: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600',
  },
  {
    id: 'puertas',
    nombre: 'Puertas',
    descripcion: 'Puertas de entrada, corredizas de patio y plegadizas. Chapa, aluminium y PVC.',
    icono: 'DoorOpen',
    imagen: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600',
  },
  {
    id: 'perfiles',
    nombre: 'Perfiles',
    descripcion: 'Perfiles de aluminium y PVC para proyectos y refacciones. Marcos, Barros y angulares.',
    icono: 'Rows',
    imagen: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600',
  },
  {
    id: 'accesorios',
    nombre: 'Accesorios',
    descripcion: 'Herrajes, ruedas, cerraduras, burletes y complementos para instalaciones.',
    icono: 'Wrench',
    imagen: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600',
  },
]

export const pedidos: Pedido[] = [
  {
    id: 'ABK-001',
    cliente: 'María González',
    email: 'maria.gonzalez@gmail.com',
    telefono: '+54 9 341 555 1234',
    productos: [
      { producto: productos[0], cantidad: 2 },
      { producto: productos[5], cantidad: 1 },
    ],
    total: 151500,
    estado: 'enviado',
    guia: 'AR123456789',
    fechaCreacion: '2026-04-10T09:30:00Z',
    fechaActualizacion: '2026-04-14T16:00:00Z',
  },
  {
    id: 'ABK-002',
    cliente: 'Carlos Rodríguez',
    email: 'carlos.rodriguez@outlook.com',
    telefono: '+54 9 11 4444 5678',
    productos: [
      { producto: productos[1], cantidad: 1 },
    ],
    total: 42500,
    estado: 'fabricacion',
    fechaCreacion: '2026-04-12T14:20:00Z',
    fechaActualizacion: '2026-04-12T14:20:00Z',
  },
  {
    id: 'ABK-003',
    cliente: 'Ana Martínez',
    email: 'anamartinez@correo.com',
    telefono: '+54 9 351 777 8901',
    productos: [
      { producto: productos[7], cantidad: 5 },
      { producto: productos[10], cantidad: 2 },
    ],
    total: 96500,
    estado: 'listo',
    fechaCreacion: '2026-04-08T11:45:00Z',
    fechaActualizacion: '2026-04-15T10:00:00Z',
  },
  {
    id: 'ABK-004',
    cliente: 'Pedro Sánchez',
    email: 'pedro.sanchez@yahoo.com',
    telefono: '+54 9 261 333 4567',
    productos: [
      { producto: productos[3], cantidad: 1 },
    ],
    total: 78000,
    estado: 'fabricacion',
    fechaCreacion: '2026-04-14T08:15:00Z',
    fechaActualizacion: '2026-04-14T08:15:00Z',
  },
  {
    id: 'ABK-005',
    cliente: 'Laura Fernández',
    email: 'laura.fernandez@gmail.com',
    telefono: '+54 9 381 999 0123',
    productos: [
      { producto: productos[5], cantidad: 1 },
      { producto: productos[11], cantidad: 2 },
    ],
    total: 163000,
    estado: 'enviado',
    guia: 'AR987654321',
    fechaCreacion: '2026-04-06T16:30:00Z',
    fechaActualizacion: '2026-04-13T12:00:00Z',
  },
]